config/routes.rb
Rails.application.routes.draw do
  resources :booking_tours
  resources :tour_reviews
  get 'home_pages/home'
  get 'users/show'
  devise_for :users
  resources :tours
  get 'tours/:id/new_review', to: 'tour_reviews#review', as: 'review_path'
  get 'tours/:id/new', to: 'booking_tours#book_tour', as: 'book_tour_path'
  root to:'home_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking_tour.rb
class BookingTour < ApplicationRecord
    belongs_to :tour
end

app/controllers/booking_tours_controller.rb
class BookingToursController < ApplicationController
  before_action :set_booking_tour, only: [:show, :edit, :update, :destroy]
  before_action :set_my_booking, only: [:index]
  before_action :set_book_tour, only: [:book_tour]
  # GET /booking_tours
  # GET /booking_tours.json
  def index
    @booking_tours = BookingTour.all
  end

  # GET /booking_tours/1
  # GET /booking_tours/1.json
  def show
  end

  # GET /booking_tours/new
  def new
    @booking_tour = BookingTour.new
  end
  
  def book_tour
    @booking_tour = BookingTour.new
    render 'book_tour'
  end

  # GET /booking_tours/1/edit
  def edit
  end

  # POST /booking_tours
  # POST /booking_tours.json
  def create
    @booking_tour = BookingTour.new(booking_tour_params)
    # need change after
    @tour = Tour.find(@booking_tour.tour_id)
    @user = User.find(@booking_tour.user_id)
    @booking_tour.total_cost = params[:booking_tour][:number_of_people].to_i*@tour.price.to_i
    respond_to do |format|
      if @booking_tour.save
        format.html { redirect_to @booking_tour, notice: 'Booking tour was successfully created.' }
        format.json { render :show, status: :created, location: @booking_tour }
      else
        format.html { render :new }
        format.json { render json: @booking_tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_tours/1
  # PATCH/PUT /booking_tours/1.json
  def update
        @booking_tour.total_cost = @booking_tour.number_of_people.to_i*@tour.price.to_i
      respond_to do |format|
      if @booking_tour.update(booking_tour_params)
        format.html { redirect_to @booking_tour, notice: 'Booking tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking_tour }
      else
        format.html { render :edit }
        format.json { render json: @booking_tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_tours/1
  # DELETE /booking_tours/1.json
  def destroy
    @booking_tour.destroy
    respond_to do |format|
      format.html { redirect_to booking_tours_url, notice: 'Booking tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_tour
      @booking_tour = BookingTour.find(params[:id])
      # @my_bookings = BookingTour.find(:all, conditions => {:user_id => current_user.id}) 
      @tour = Tour.find(@booking_tour.tour_id)
      @user = User.find(@booking_tour.user_id)
    end

    def set_my_booking
        @my_bookings = current_user.booking_tour
    end

    def set_book_tour
      @tour = Tour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_tour_params
      params.require(:booking_tour).permit(:user_id, :tour_id, :number_of_people, :vehicle)
    end
  
end

app/helpers/booking_tours_helper.rb
module BookingToursHelper
end

app/views/booking_tours/_form.html.erb
<%= form_with(model: booking_tour, local: true) do |form| %>
  <% if booking_tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking_tour.errors.count, "error") %> prohibited this booking_tour from being saved:</h2>
      <ul>
        <% booking_tour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <!--need change after that-->

  <div class="field">
    <%= form.hidden_field :tour_id, value: @tour.id%>
  </div>

  
  <div class="field">
    <%= form.label :人の数 %>
    <%= form.number_field :number_of_people %>
  </div>

  <div class="field">
  　<%= form.label :vehicle, "どうやって行きたいですか？" %><br/>
  　<%= form.select :vehicle, options_for_select(["バスで","飛行機で","船で","電車で"]) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/booking_tours/book_tour.html.erb
<h1>New Booking Tour</h1>

<%= render 'form', booking_tour: @booking_tour %>

<%= link_to 'Back', booking_tours_path %>

app/views/booking_tours/edit.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
      <div class="authen__container">
<h1>Editing Booking Tour</h1>

<%= render 'form', booking_tour: @booking_tour %>

<%= link_to '表示', @booking_tour %> |
<%= link_to '戻る', booking_tours_path %> 
</div>
</div>

app/views/booking_tours/index.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<h1 style="margin-bottom: 10px; text-align: center; display: block">Booking Tours</h1>
<p id="notice"><%= notice %></p>

  <% if current_user.is_admin %>
<h1>All Booking</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Tour</th>
      <th>Booking Details</th>
      <th>Booking At</th>
    </tr>
  </thead>

  <tbody>

    <% @booking_tours.each do |booking_tour| %>
      <% @user = User.find(booking_tour.user_id)%>
      <% @tour = Tour.find(booking_tour.tour_id)%>
      <tr>
        <td><%= link_to @user.name, users_show_path(@user) %></td>
        <td><%= @user.email %></td>
        <td><%= @tour.title %></td>
        <td><%= link_to @tour.title, tour_path(@tour) %></td>
        <td><%= booking_tour.created_at.strftime("%B %d %Y")%></td>
      </tr>
     
        
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking Tour', new_booking_tour_path %>
 
  <% elsif %>
  <h1><%= current_user.name %>'s Booking</h1>
  <%if !@my_bookings %>
      <p>You have never booking before. <%= link_to 'Booking now!', new_booking_tour_path%> </p>
    <% elsif %>
<table>
  <thead>
    <tr>
      <th>Tour</th>
      <th>Tour Name</th>
      <th>Total Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_bookings.each do |booking_tour| %>
    <% @tour = Tour.find(booking_tour.tour_id) %>
      <tr>
        <td><%= booking_tour.tour_id %></td>
        <td><%= @tour.title %></td>
        <td><%=booking_tour.total_cost%></td>
        <td><%= link_to 'Show', booking_tour %></td>
        <td><%= link_to 'Edit', edit_booking_tour_path(booking_tour) %></td>
        <td><%= link_to 'Unbooking', booking_tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  <% end %>
  </tbody>
</table>

<% end %>
</div>
</div>

app/views/booking_tours/new.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<h1 style="margin-bottom: 10px; text-align: center; display: block">New Booking Tour</h1>

<%= render 'form', booking_tour: @booking_tour %>

<%= link_to 'Back', booking_tours_path %>
</div>
</div>

app/views/booking_tours/show.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
      <div class="authen__container">
<p id="notice"><%= notice %></p>

<h1 style="margin-bottom: 15px; text-align: center; display: block">Tour Detail</h1>
<p>
<strong>User:</strong>
  <%= @booking_tour.user_id %>
</p>

<p>
  <strong>ツアー：</strong>
  <%= @booking_tour.tour_id %>
</p>

<p>
  <strong>人の数:</strong>
  <%= @booking_tour.number_of_people %>
</p>

<p>
  <strong>交通</strong>
  <%= @booking_tour.vehicle %>
</p>

<!--need to edit after-->
<p>
  <strong> 合計 </strong>
  <%= @booking_tour.total_cost %>
</p>


<%= link_to 'Edit', edit_booking_tour_path(@booking_tour) %> |
<%= link_to 'Back', booking_tours_path %>
</div>
</div>