config/routes.rb
Rails.application.routes.draw do
  resources :booking_tours
  resources :tour_reviews
  get 'home_pages/home'
  get 'users/show'
  devise_for :users
  resources :tours
  get 'tours/:id/new_review', to: 'tour_reviews#review', as: 'review_path'
  get 'tours/:id/new', to: 'booking_tours#book_tour', as: 'book_tour_path'
  root to:'home_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_one_attached :image
    has_many :tour_review, -> { order "created_at DESC"}
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
 
  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end
  def show 
    @reviews = @tour.tour_review
  end
  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tour_params
      params.require(:tour).permit(:title, :time, :description, :price, :image)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
        <% tour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div class="field">
    <%= form.label :time %>
    <%= form.number_field :time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<p id="notice"><%= notice %></p>

<h1 style="margin-bottom: 15px; text-align: center; display: block">Tours</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Time</th>
      <th>Description</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.title %></td>
        <td><%= tour.time %></td>
        <td><%= tour.description %></td>
        <td><%= link_to 'Show', tour %></td>
          
         <% if user_signed_in? %>
        <% if current_user.is_admin? %>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to 'Booking', book_tour_path_url(tour.id) %></td>
        <% end %>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<% if current_user.is_admin? %>
<%= link_to 'New Tour', new_tour_path %>



<% end %>
<% end %>
    </div>
</div>

app/views/tours/new.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<h1 style="margin-bottom: 20px; text-align: center; display: block">New Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>
</div>
</div>

app/views/tours/show.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<p id="notice"><%= notice %></p>


  <%= image_tag(@tour.image, style:"width: 650px; height: 400px") if @tour.image.attached? %>

<p>
  <strong>Title:</strong>
  <%= @tour.title %>
</p>

<p>
  <strong>Time:</strong>
  <%= @tour.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tour.price %> VND
</p>

<p>
   <% if @tour.image.attached? %>
     <%= image_tag @tour.image %>
   <% end %>
 </p>
 
 
 <%= link_to 'New Review', review_path_url(@tour.id) %>
  <%= link_to 'Edit', edit_tour_path(@tour) %> |
  <%= link_to 'Back', tours_path %>
 </br>
 </br>
 <p><em>ALL REVIEWS</em></p>
  <table>
    <th>User name</th>
    <th>Comment</th>
  <% @reviews.each do |review| %>
      <% @user = User.find(review.user_id)%>
      <tr>
        <td><%= link_to @user.name, users_show_path(@user) %></td>
        <td><%= review.review%></td>
      </tr>
  <% end %>
      </table>
</div>
</div>