config/routes.rb
Rails.application.routes.draw do
  resources :booking_tours
  resources :tour_reviews
  get 'home_pages/home'
  get 'users/show'
  devise_for :users
  resources :tours
  get 'tours/:id/new_review', to: 'tour_reviews#review', as: 'review_path'
  get 'tours/:id/new', to: 'booking_tours#book_tour', as: 'book_tour_path'
  root to:'home_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/tour_reviews_controller.rb
class TourReviewsController < ApplicationController
  before_action :set_tour_review, only: [:show, :edit, :update, :destroy]
 before_action :set_review, only: [:review]
  # GET /tour_reviews
  # GET /tour_reviews.json
  
  
  
  def index
    @tour_reviews = TourReview.all
  end

  # GET /tour_reviews/1
  # GET /tour_reviews/1.json
  def show
    @tour_reviews = TourReview.new
  end

  def review
    @tour_reviews = TourReview.new
    render 'review'
  end

  # GET /tour_reviews/new
  def new
    @tour_review = TourReview.new
  end

  # GET /tour_reviews/1/edit
  def edit
  end

  # POST /tour_reviews
  # POST /tour_reviews.json
  def create
    @tour_review = TourReview.new(tour_review_params)

    respond_to do |format|
      if @tour_review.save
        format.html { redirect_to tours_url(current_user.id), notice: 'ツアーレビューが正常に作成されました。' }
        #format.json { render :show, status: :created, location: @tour_review }
      else
        format.html { render :new }
        format.json { render json: @tour_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_reviews/1
  # PATCH/PUT /tour_reviews/1.json
  def update
    respond_to do |format|
      if @tour_review.update(tour_review_params)
        format.html { redirect_to @tour_review, notice: 'ツアーレビューが正常に更新されました。' }
        format.json { render :show, status: :ok, location: @tour_review }
      else
        format.html { render :edit }
        format.json { render json: @tour_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_reviews/1
  # DELETE /tour_reviews/1.json
  def destroy
    @tour_review.destroy
    respond_to do |format|
      format.html { redirect_to tour_reviews_url, notice: 'ツアーレビューは正常に削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_review
      @tour_review = TourReview.find(params[:id])
    end

    def set_review
      @tour = Tour.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def tour_review_params
      params.require(:tour_review).permit(:user_id, :tour_id, :review)
    end
end

app/helpers/tour_reviews_helper.rb
module TourReviewsHelper
end

app/views/tour_reviews/_form.html.erb
<%= form_with(model: @tour_reviews, local: true) do |form| %>
  <% if @tour_reviews.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour_review.errors.count, "error") %> prohibited this tour_review from being saved:</h2>

      <ul>
        <% tour_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

   <div class="field">
    <%= form.hidden_field :tour_id, value: @tour.id %>
  </div>
  
  <div class="field">
    <%= form.label :review, 'レビュー' %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit '参加する'  %>
  </div>
<% end %>

app/views/tour_reviews/edit.html.erb
<h1>ツアーレビューの編集</h1>

<%= render 'form', tour_review: @tour_review %>

<%= link_to '表示', @tour_review %> |
<%= link_to 'バック', tour_reviews_path %>

app/views/tour_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<h1 style="margin-bottom: 10px; text-align: center; display: block">ツアーレビュー</h1>

<table>
  <thead>
    <tr>
      <th>ユーザー</th>
      <th>ツアー</th>
      <th>レビュー</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tour_reviews.each do |tour_review| %>
      <tr>
        <td><%= tour_review.user_id %></td>
        <td><%= tour_review.tour_id %></td>
        <td><%= tour_review.review %></td>
        <td><%= link_to '表示', tour_review %></td>
        <td><%= link_to '編集', edit_tour_review_path(tour_review) %></td>
        <td><%= link_to '削除', tour_review, method: :delete, data: { confirm: '本気ですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ツアーレビューを作成する', new_tour_review_path %>
</div>
</div>

app/views/tour_reviews/new.html.erb
<div class="section__container">
      <h1 class="homepage__hero">Welcome to heaven trip</h1>
    <p class="homepage__description">You want go to heaven when you die?</p>
    <p class="homepage__subscription">This is for you! </p>
  <div class="authen__container">
<h1 style="margin-bottom: 15px; text-align: center; display: block">ツアーレビューを作成する</h1>

<%= render 'form', tour_review: @tour_review %>

<%= link_to 'バック', tour_reviews_path %>
</div>
</div>

app/views/tour_reviews/review.html.erb
<h1>New Booking Tour</h1>

<%= render 'form', booking_tour: @booking_tour %>

<%= link_to 'Back', booking_tours_path %>

app/views/tour_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ユーザー：</strong>
  <%= @tour_review.user_id %>
</p>

<p>
  <strong>ツアー：</strong>
  <%= @tour_review.tour_id %>
</p>

<p>
  <strong>レビュー：</strong>
  <%= @tour_review.review %>
</p>

<%= link_to '編集', edit_tour_review_path(@tour_review) %> |
<%= link_to 'バック', tour_reviews_path %>